### ISSUE TITLE
Blues stack start checklist

### ISSUE THREAD

**Issue by sirinoks** [DevelopingSpace/starchart#51]
We are having multiple problems with this, so I made a checklist of issues to keep track.

- [x] [Add initial code (issue)](https://github.com/Seneca-CDOT/starchart/issues/7):
- [x] [Add blues stack PR](https://github.com/Seneca-CDOT/starchart/pull/38)

---

- [ ] [Create documentation how to run it (issue)](https://github.com/Seneca-CDOT/starchart/issues/12):
- [x] [Initial documentation started](https://github.com/Seneca-CDOT/starchart/wiki/%5BUnder-construction%5D-Set-up-documentation)
- [x] ~~[Fix a bug with docker and database](https://github.com/Seneca-CDOT/starchart/pull/40) | @Ririio 's setup attempt~~ - more of a database issue rather than blue stack
- [x] [Fix a bug with startup configuration (issue)](https://github.com/Seneca-CDOT/starchart/issues/52) | @shawnyu5 setup attempt
- [x] Update documentation and code until people can reliably setup their projects

**Comment by sirinoks** [comment]
@shawnyu5 Do we have documentation for this? I forgot what's our progress

**Comment by shawnyu5** [comment]
>  Update documentation and code until people can reliably setup their projects

this was addressed in our contributing.md
